
name: File Converter CI-CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      ENV: test
      DATABASE_URL: sqlite+aiosqlite://
      DATABASE_URL_SYNC: sqlite://
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/file-converter-api:latest .

      
      - name: Run Tests
        run: |
          docker run --rm \
          -e ENV=test \
          -e DATABASE_URL=sqlite+aiosqlite:// \
          -e DATABASE_URL_SYNC=sqlite:// \
          -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          ${{ secrets.DOCKER_USERNAME }}/file-converter-api:latest pytest -v

     
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      
      - name: Push Image
        if: github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKER_USERNAME }}/file-converter-api:latest

       
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}



